name: CI/CD Pipeline - Laravel Docker Deployment

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/laravel-todolist

jobs:
  # JOB 1: Build & Push ke Docker Hub
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:1.0.0
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

  deploy-local:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Inject .env File from GitHub Secrets
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull Latest Docker Image
        run: |
          docker compose pull app

      - name: Restart Containers
        run: |
          docker compose down
          docker compose up -d

      - name: Fix Permissions & Ensure SQLite Exists
        run: |
          docker compose exec -T -u root app touch /var/www/html/database/database.sqlite
          docker compose exec -T -u root app chown -R www-data:www-data /var/www/html/.env /var/www/html/database /var/www/html/storage
          docker compose exec -T -u root app chmod -R 775 /var/www/html/.env /var/www/html/database /var/www/html/storage

      - name: Generate App Key & Run Migrations
        run: |
          docker compose exec -T app php artisan migrate --force
          docker compose exec -T app php artisan config:clear
          docker compose exec -T app php artisan route:clear